stages:
  - ci
  - deploy

############################
# windows pipeline
# "call" is mandatory, see https://gitlab.com/gitlab-org/gitlab-runner/issues/1051
############################
ci:windows:
  stage: ci
  script:
    - call "%CI_PROJECT_DIR%\\deploy\\windows\\build.bat"
  allow_failure: false
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\ci-install"
    expire_in: 1 hrs
  tags:
    - windows
    - windows7

deploy:windows:
  stage: deploy
  script:
    - call "%CI_PROJECT_DIR%\\BuildServer\\Windows\\deploy.bat"
  dependencies:
    - ci:windows
  allow_failure: false
  only:
    - master
    - develop
    - tags
  when: on_success
  artifacts:
    paths:
     - "C:\\temp\bastion_browser_install\\*.exe"
  tags:
    - windows
    - windows7
