stages:
  - ci
  - deploy

############################
# windows pipeline
# "call" is mandatory, see https://gitlab.com/gitlab-org/gitlab-runner/issues/1051
############################
ci:windows:
  stage: ci
  script:
    - call "%CI_PROJECT_DIR%\\deploy\\windows\\build.bat" 
  allow_failure: false
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\ci-install"
    expire_in: 1 hrs
  tags:
    - windows
    - windows7

deploy:windows:
  stage: deploy
  script:
    - call "%CI_PROJECT_DIR%\\deploy\\windows\\deploy.bat"
  dependencies:
    - ci:windows
  allow_failure: false
  only:
    - master
    - develop
    - tags
  when: on_success
  artifacts:
    paths:
     - "%CI_PROJECT_DIR%\\ci-install\\passhfiles-%CI_COMMIT_REF_NAME%-win-amd64.exe"
  tags:
    - windows
    - windows7

############################
# macos pipeline
############################
ci:macos:
  stage: ci
  script:
    - chmod u+x ${CI_PROJECT_DIR}/deploy/macos/build.sh
    - ${CI_PROJECT_DIR}/BuildServer/deploy/macos/build.sh
  allow_failure: false
  artifacts:
    paths:
    - "%CI_PROJECT_DIR%\\dist"
    expire_in: 1 hrs
  tags:
    - macos

deploy:macos:
  stage: deploy
  script:
    - chmod u+x ${CI_PROJECT_DIR}/deploy/macos/deploy.sh
    - ${CI_PROJECT_DIR}/deploy/macos/deploy.sh
  dependencies:
    - ci:macos
  allow_failure: false
  only:
    - master
    - develop
    - tags
  when: on_success
  artifacts:
    paths:
     - ${CI_PROJECT_DIR}/deploy/macos/passhfiles-${CI_COMMIT_REF_NAME}-macOS-amd64.dmg"
  tags:
    - macos
